//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xalag.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xalag.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خلاق.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برگشت.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برگشت به مرحله قبل.
        /// </summary>
        public static string BackToPreviewsStep {
            get {
                return ResourceManager.GetString("BackToPreviewsStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ تولد.
        /// </summary>
        public static string Birthday {
            get {
                return ResourceManager.GetString("Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خرید بلیت.
        /// </summary>
        public static string BuyTicket {
            get {
                return ResourceManager.GetString("BuyTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تبریز، آبرسان، کلانتر کوچه، کوی دوم.
        /// </summary>
        public static string CompanyAddress {
            get {
                return ResourceManager.GetString("CompanyAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تماس با ما.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سوالات متداول.
        /// </summary>
        public static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اغلب مهارت های کودکان در سن 4 و 5 سالگی شکل می گیرند و رشد می کند. بازسازی و اصلاح این مهارت ها در سنین پایین تر بهتر صورت می گیرد..
        /// </summary>
        public static string FirstSubTitle {
            get {
                return ResourceManager.GetString("FirstSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شعله های اشتیاق و علاقه به یادگیری را در وجود فرزندتان فروزان کنید.
        /// </summary>
        public static string FirstTitle {
            get {
                return ResourceManager.GetString("FirstTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سوال و جواب های متداول.
        /// </summary>
        public static string FrequentlyAskedQuestions {
            get {
                return ResourceManager.GetString("FrequentlyAskedQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خانه.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خردسالی کودک خود را از دست ندهید.
        /// </summary>
        public static string ImageSubTilte1 {
            get {
                return ResourceManager.GetString("ImageSubTilte1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کودکانتان را از وابستگی به خود برهانید.
        /// </summary>
        public static string ImageSubTilte2 {
            get {
                return ResourceManager.GetString("ImageSubTilte2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ما ، هر مهارت و مفهومی را با بازی یاد میدهیم.
        /// </summary>
        public static string ImageSubTilte3 {
            get {
                return ResourceManager.GetString("ImageSubTilte3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام خانوادگی.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداکثر تعداد رزرو صندلی برای کاربر.
        /// </summary>
        public static string MaxReservedChairPerUser {
            get {
                return ResourceManager.GetString("MaxReservedChairPerUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موبایل.
        /// </summary>
        public static string MobileNo {
            get {
                return ResourceManager.GetString("MobileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره موبایل باید {2} رقم و بدون 0 اولیه باشد..
        /// </summary>
        public static string MobileNoMustBe_2_Digit {
            get {
                return ResourceManager.GetString("MobileNoMustBe_2_Digit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ModernBusinessFeatures1 {
            get {
                return ResourceManager.GetString("ModernBusinessFeatures1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یک کار اصولی لازم بود که بچه های گلمان؛ از همین ابتدا....
        /// </summary>
        public static string ModernBusinessFeatures1_1 {
            get {
                return ResourceManager.GetString("ModernBusinessFeatures1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درس را، زندگی را و ریاضی را خوب یاد بگیرند..
        /// </summary>
        public static string ModernBusinessFeatures1_2 {
            get {
                return ResourceManager.GetString("ModernBusinessFeatures1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to و برای حضور در دبیرستان، آماده شوند..
        /// </summary>
        public static string ModernBusinessFeatures1_3 {
            get {
                return ResourceManager.GetString("ModernBusinessFeatures1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یک آمادگی که با شور و نشاط و عشق به یادگیری همراه باشد....
        /// </summary>
        public static string ModernBusinessFeatures1_4 {
            get {
                return ResourceManager.GetString("ModernBusinessFeatures1_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آمده ایم و طرحی نو در انداخته ایم.
        /// </summary>
        public static string ModernBusinessFeatures1_5 {
            get {
                return ResourceManager.GetString("ModernBusinessFeatures1_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to و یک پیش دبستانی با تخصصی ترین رویکرد یعنی «هوش و خلاقیت ریاضی» تأسیس نموده ایم..
        /// </summary>
        public static string ModernBusinessFeatures1_6 {
            get {
                return ResourceManager.GetString("ModernBusinessFeatures1_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یکی از شعارهایمان این است که کودک را در حساس ترین سن یادگیری تنها نگذاریم!.
        /// </summary>
        public static string ModernBusinessFeatures1_7 {
            get {
                return ResourceManager.GetString("ModernBusinessFeatures1_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اینک از شما میخواهیم در رویداد بزرگ افتتاح این مرکز، ما را تنها نگذارید..
        /// </summary>
        public static string ModernBusinessFeatures1_8 {
            get {
                return ResourceManager.GetString("ModernBusinessFeatures1_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اگر میخواهید کودکتان پایه ریاضی بهتری داشته باشد.
        /// </summary>
        public static string ModernBusinessFeatures2_1 {
            get {
                return ResourceManager.GetString("ModernBusinessFeatures2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اگر میخواهید کودکتان از همین امروز شیب ملایم تیزهوشان و نمونه دولتی را شروع کند.
        /// </summary>
        public static string ModernBusinessFeatures2_10 {
            get {
                return ResourceManager.GetString("ModernBusinessFeatures2_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اگر میخواهید رابطه ی بین شما و فرزندتان قوی و پایدار باشد.
        /// </summary>
        public static string ModernBusinessFeatures2_2 {
            get {
                return ResourceManager.GetString("ModernBusinessFeatures2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اگر میخواهید کودکتان را از وابستگی به خود رها سازید.
        /// </summary>
        public static string ModernBusinessFeatures2_3 {
            get {
                return ResourceManager.GetString("ModernBusinessFeatures2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اگر میخواهید کودکتان برنامه ریزی کودکانه را یاد بگیرد.
        /// </summary>
        public static string ModernBusinessFeatures2_4 {
            get {
                return ResourceManager.GetString("ModernBusinessFeatures2_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اگر میخواهید دقت و تمرکز کودکتان افزایش یابد.
        /// </summary>
        public static string ModernBusinessFeatures2_5 {
            get {
                return ResourceManager.GetString("ModernBusinessFeatures2_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اگر میخواهید فرزندتان برای حضور در مدرسه آماده شود.
        /// </summary>
        public static string ModernBusinessFeatures2_6 {
            get {
                return ResourceManager.GetString("ModernBusinessFeatures2_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اگر میخواهید کودکتان یادگیری را بدون استرس انجام دهد.
        /// </summary>
        public static string ModernBusinessFeatures2_7 {
            get {
                return ResourceManager.GetString("ModernBusinessFeatures2_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اگر میخواهید کودکتان انسانی معنوی و پاکدامن و درستکار تربیت شود.
        /// </summary>
        public static string ModernBusinessFeatures2_8 {
            get {
                return ResourceManager.GetString("ModernBusinessFeatures2_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اگر میخواهید کودکتان متناسب با توانایی های خود و مطابق استانداردهای علمی رشد کند.
        /// </summary>
        public static string ModernBusinessFeatures2_9 {
            get {
                return ResourceManager.GetString("ModernBusinessFeatures2_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رویکرد هوش و خلاقیت ریاضی.
        /// </summary>
        public static string ModernBusinessTitle1 {
            get {
                return ResourceManager.GetString("ModernBusinessTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کار ما آموزش است نه نگهداری.
        /// </summary>
        public static string ModernBusinessTitle2 {
            get {
                return ResourceManager.GetString("ModernBusinessTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی.
        /// </summary>
        public static string NatrualCode {
            get {
                return ResourceManager.GetString("NatrualCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی باید {2} رقمی باشد!.
        /// </summary>
        public static string NatrualCodeMustBe_2_Digit {
            get {
                return ResourceManager.GetString("NatrualCodeMustBe_2_Digit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد صندلی.
        /// </summary>
        public static string NumberOfSeats {
            get {
                return ResourceManager.GetString("NumberOfSeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ... وای! چیزی گم شده است.
        /// </summary>
        public static string Oops_Something_is_missing {
            get {
                return ResourceManager.GetString("Oops_Something_is_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفحه ی مورد نظر پیدا نشد.
        /// </summary>
        public static string PageNotFound {
            get {
                return ResourceManager.GetString("PageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه مکان.
        /// </summary>
        public static string PlaceId {
            get {
                return ResourceManager.GetString("PlaceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام مکان.
        /// </summary>
        public static string PlaceName {
            get {
                return ResourceManager.GetString("PlaceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لذت یادگیری را به فرزندتان بچشانید.
        /// </summary>
        public static string PortofilioTitle {
            get {
                return ResourceManager.GetString("PortofilioTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ما همه ی مفاهیم و مهارت های مورد نیاز را توسط بازی یاد می دهیم.
        ///اولین موردی که برای «کودک» مورد نیاز است ، شور و هیجان یادگیری است نه آموزش های مستقیم و بدون هیجان!.
        /// </summary>
        public static string SecondSubTilte {
            get {
                return ResourceManager.GetString("SecondSubTilte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موثر ترین راه یادگیری در کودکتان غیر مستقیم ترین راه است.
        /// </summary>
        public static string SecondTilte {
            get {
                return ResourceManager.GetString("SecondTilte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ اجلاس.
        /// </summary>
        public static string SessionDateTime {
            get {
                return ResourceManager.GetString("SessionDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زیرعنوان.
        /// </summary>
        public static string SubTitle {
            get {
                return ResourceManager.GetString("SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلد {0} الزامی است.
        /// </summary>
        public static string The_0_field_is_required {
            get {
                return ResourceManager.GetString("The_0_field_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to از همین «کودکی» باید «کودک» برای درک معانی ریاضیات آماده شود.
        ///بهتر است «کودک» با مفهوم آزمایش در علوم آشنا شود..
        /// </summary>
        public static string ThirdParty1 {
            get {
                return ResourceManager.GetString("ThirdParty1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to که از همان کودکی «برنامه ریز» باشند که بتوانند «نظم» را پیدا کنند که «صبوری» را درک کنند که «نظافت» و «آراستگی» را کشف کنند و ریاضیات را اصولی تر یاد بگیرند..
        /// </summary>
        public static string ThirdParty2 {
            get {
                return ResourceManager.GetString("ThirdParty2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کافی است ما دنیای کودکان را درک کنیم.
        ///ما، کودک را برای زندگی در مدرسه آماده می کنیم.
        ///و با ابزار های اندیشه و درس که سالهای دبستان به آنها نیاز خواهد داشت آشنا می کنیم..
        /// </summary>
        public static string ThirdParty3 {
            get {
                return ResourceManager.GetString("ThirdParty3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to از همین کودکی . . ..
        /// </summary>
        public static string ThirdPartyTitle1 {
            get {
                return ResourceManager.GetString("ThirdPartyTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به کودکان «کمک» می کنیم.
        /// </summary>
        public static string ThirdPartyTitle2 {
            get {
                return ResourceManager.GetString("ThirdPartyTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کودکان دنیای مارا درک می کنند.
        /// </summary>
        public static string ThirdPartyTitle3 {
            get {
                return ResourceManager.GetString("ThirdPartyTitle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه کاربری.
        /// </summary>
        public static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ما دوست داریم صدایتان را بشنویم.
        /// </summary>
        public static string WeHadLoveToHearFromYou {
            get {
                return ResourceManager.GetString("WeHadLoveToHearFromYou", resourceCulture);
            }
        }
    }
}
